apiVersion :  v1
kind :  Service
metadata :
  name :  platform-nodeport-service
spec:
  type :  NodePort
  selector :
    app :  platformservice
  ports :
    - name: platformservice
      protocol :  TCP
      port :  80
      targetPort :  80


#  -  port :  8080
#     targetPort :  8080
#     nodePort :  30080